/* 🔮 DARKAIS QUANT TAROT — 22 MAJOR ARCANA CYBER QUANT DECK */

const TAROT_DECK = [
    {
        id: 0,
        roman: "0",
        name: "The Degenerate",
        arcana: "The Fool",
        icon: "🚀",
        element: "Entropy",
        keywords: ["100x Leverage", "Blind Faith", "Genesis Rush", "Uncalculated Risk"],
        upright: "A bold leap into the chaotic volatility of an unverified memecoin pool. Untamed potential, raw momentum, and the spirit of the fearless trader.",
        inverted: "Reckless over-leveraging into an obvious liquidity trap. Extreme risk of complete wallet wipeout.",
        alphaDirective: "Size your position with a strict stop-loss before momentum reverses.",
        sentiment: "Bullish Chaos (Risk: 95%)",
        color: "#00F0FF"
    },
    {
        id: 1,
        roman: "I",
        name: "The Algorithm",
        arcana: "The Magician",
        icon: "⚡",
        element: "Logic",
        keywords: ["Deterministic Execution", "Execution Speed", "Market Mastery", "Order Flow"],
        upright: "Mastery over high-frequency execution pipelines. All market variables are aligned for profitable latency arbitrage.",
        inverted: "Execution slip, race conditions, or stale API pricing data corrupting order routing.",
        alphaDirective: "Automate your trade entries and eliminate human emotional hesitation.",
        sentiment: "Highly Bullish (Precision: 92%)",
        color: "#39FF14"
    },
    {
        id: 2,
        roman: "II",
        name: "The Black Box",
        arcana: "The High Priestess",
        icon: "🧠",
        element: "Neural Latent Space",
        keywords: ["Deep Learning", "Hidden Patterns", "Intuition", "Latent Vectors"],
        upright: "Subtle non-linear patterns detected in high-dimensional latent space. Trust the mathematical intuition of the model.",
        inverted: "Uninterpretable hallucination or adversarial attack fooling the neural network.",
        alphaDirective: "Look beyond simple moving averages into hidden correlation matrices.",
        sentiment: "Mystical Neutral (Alpha: 84%)",
        color: "#C084FC"
    },
    {
        id: 3,
        roman: "III",
        name: "The Liquidity Pool",
        arcana: "The Empress",
        icon: "🌊",
        element: "Abundance",
        keywords: ["DeFi Yields", "Passive APR", "Organic Growth", "Deep Books"],
        upright: "Thick order book depth and compounding automated market maker fees. Sustainable organic portfolio growth.",
        inverted: "Impermanent loss surge or malicious liquidity drain (rug pull).",
        alphaDirective: "Farm yield on high-volume pairs and harvest compounding interest.",
        sentiment: "Strongly Bullish (Yield: 88%)",
        color: "#00E676"
    },
    {
        id: 4,
        roman: "IV",
        name: "The Institutional Whale",
        arcana: "The Emperor",
        icon: "🐋",
        element: "Market Depth",
        keywords: ["Market Maker", "Order Wall", "Dominance", "Accumulation"],
        upright: "Massive institutional limit orders forming an unbreakable support level. Smart money accumulation phase.",
        inverted: "Spoofing walls, aggressive price suppression, and retail stop-hunting sweeps.",
        alphaDirective: "Trade in the slipstream of whale accumulation; do not fight the trend.",
        sentiment: "Structured Bullish (Stability: 90%)",
        color: "#FFB800"
    },
    {
        id: 5,
        roman: "V",
        name: "The Satoshi",
        arcana: "The Hierophant",
        icon: "👑",
        element: "Consensus",
        keywords: ["Genesis Block", "Immutable Protocol", "Proof of Work", "Foundational Truth"],
        upright: "Unyielding cryptographic integrity. Long-term fundamental conviction in decentralized infrastructure.",
        inverted: "Outdated dogmatic trading rules that fail in modern high-frequency liquidity regimes.",
        alphaDirective: "Return to core first-principles and audited cryptographic protocols.",
        sentiment: "Macro Bullish (Conviction: 99%)",
        color: "#FFD700"
    },
    {
        id: 6,
        roman: "VI",
        name: "The Arbitrage Pair",
        arcana: "The Lovers",
        icon: "🔗",
        element: "Cointegration",
        keywords: ["Statistical Pairs", "Mean Reversion", "Dual Hedging", "Spread Compression"],
        upright: "A perfect mathematical cointegration between two synthetic assets. Low-risk statistical arbitrage opportunity.",
        inverted: "Breakdown of historical correlation, causing divergence loss in a pair trade.",
        alphaDirective: "Hedge directional exposure by longing the undervalued and shorting the overvalued.",
        sentiment: "Delta Neutral (Alpha: 89%)",
        color: "#00F0FF"
    },
    {
        id: 7,
        roman: "VII",
        name: "100x Leverage Rocket",
        arcana: "The Chariot",
        icon: "🏎️",
        element: "Velocity",
        keywords: ["Parabolic Drive", "Unstoppable Trend", "Breakout Speed", "Full Throttle"],
        upright: "Explosive breakout momentum breaking through all overhead resistance. Ride the parabolic surge.",
        inverted: "Loss of vehicle control, extreme slippage, and reckless margin overextension.",
        alphaDirective: "Trail your stop loss tightly as velocity reaches hyper-extended highs.",
        sentiment: "Parabolic Surge (Velocity: 94%)",
        color: "#FF3366"
    },
    {
        id: 8,
        roman: "VIII",
        name: "Diamond Hands",
        arcana: "Strength",
        icon: "💎",
        element: "Fortitude",
        keywords: ["Unflinching Hold", "Drawdown Resilience", "Emotional Mastery", "Patience"],
        upright: "Indomitable psychological resilience through extreme market drawdowns. The storm passes; value remains.",
        inverted: "Stubbornly holding an objectively dying asset due to emotional ego.",
        alphaDirective: "Calm your nervous system; market volatility is merely noise for the patient.",
        sentiment: "Stoic Bullish (Resilience: 96%)",
        color: "#00F0FF"
    },
    {
        id: 9,
        roman: "IX",
        name: "The Quant Researcher",
        arcana: "The Hermit",
        icon: "🔬",
        element: "Solitude",
        keywords: ["Backtesting", "Mathematical Rigor", "Hypothesis Audit", "Deep Focus"],
        upright: "Solitary mathematical study yielding a brand-new proprietary alpha indicator. Truth discovered in data.",
        inverted: "Overfitting to past noise, isolation in theoretical models with zero market viability.",
        alphaDirective: "Verify statistical significance (p < 0.01) before allocating real capital.",
        sentiment: "Analytical Neutral (Depth: 91%)",
        color: "#A855F7"
    },
    {
        id: 10,
        roman: "X",
        name: "The Market Cycle",
        arcana: "Wheel of Fortune",
        icon: "🎡",
        element: "Cyclicality",
        keywords: ["Bull/Bear Rotation", "Karma", "Liquidity Shifts", "Kondratiev Waves"],
        upright: "A sudden favorable rotation of macro liquidity into your chosen asset class.",
        inverted: "A brutal cyclical downturn; the bottom falls out as liquidity evaporates.",
        alphaDirective: "Take profits on euphoric expansions; re-accumulate during capitulation despair.",
        sentiment: "Macro Turning Point (Flux: 85%)",
        color: "#FFB800"
    },
    {
        id: 11,
        roman: "XI",
        name: "The Smart Contract",
        arcana: "Justice",
        icon: "⚖️",
        element: "Equilibrium",
        keywords: ["Code is Law", "Deterministic Logic", "Audited Balance", "Zero Bias"],
        upright: "Fair, unbribable, and deterministic settlement. The mathematical truth always reasserts itself.",
        inverted: "Unchecked smart contract exploit, reentrancy vulnerability, or frozen state.",
        alphaDirective: "Audit your risk parameters and ensure mathematical equity across trades.",
        sentiment: "Pure Equilibrium (Fair Value: 100%)",
        color: "#39FF14"
    },
    {
        id: 12,
        roman: "XII",
        name: "Trapped Liquidity",
        arcana: "The Hanged Man",
        icon: "⏳",
        element: "Suspension",
        keywords: ["Staked Lockup", "Patience Required", "Alternative Perspective", "Epoch Waiting"],
        upright: "A temporary strategic freeze allowing long-term compounding yields to mature.",
        inverted: "Futile sacrifice of liquidity while high-opportunity yield passes by elsewhere.",
        alphaDirective: "Step back and observe the market with zero active positions for a fresh perspective.",
        sentiment: "Contemplative Freeze (Patience: 80%)",
        color: "#64748B"
    },
    {
        id: 13,
        roman: "XIII",
        name: "The Liquidation",
        arcana: "Death",
        icon: "💀",
        element: "Rebirth",
        keywords: ["Margin Call", "Total Wipeout", "Metamorphosis", "Tabula Rasa"],
        upright: "The painful clearing of bad leverage. Creative destruction that purges weak hands and births a new super-cycle.",
        inverted: "Lingering slow bleeding drawdown; refusal to accept a loss and cut the trade.",
        alphaDirective: "Cut losing trades immediately. Capital preservation is the only law of survival.",
        sentiment: "Catastrophic Rebirth (Reset: 99%)",
        color: "#FF0055"
    },
    {
        id: 14,
        roman: "XIV",
        name: "The Risk Manager",
        arcana: "Temperance",
        icon: "🛡️",
        element: "Harmony",
        keywords: ["Kelly Criterion", "Position Sizing", "Diversification", "Calm Balance"],
        upright: "Flawless risk-to-reward ratio. Controlled position sizing that guarantees long-term geometric capital growth.",
        inverted: "Over-allocating to a single high-risk asset, leading to severe portfolio instability.",
        alphaDirective: "Never risk more than 1.5% of total portfolio equity on any single trade.",
        sentiment: "Golden Balance (Sharpe: 95%)",
        color: "#00E676"
    },
    {
        id: 15,
        roman: "XV",
        name: "FOMO & Greed",
        arcana: "The Devil",
        icon: "😈",
        element: "Bondage",
        keywords: ["Chasing ATH", "Euphoria Trap", "Revenge Trading", "Addiction"],
        upright: "Being seduced by green candles at local tops. Trading on raw dopamine rather than calculated alpha.",
        inverted: "Breaking free from trading addiction, recognizing the trap, and stepping aside.",
        alphaDirective: "If you feel the desperate urge to buy because everyone is bragging, SELL instead.",
        sentiment: "Extreme Greed (Danger Alert: 98%)",
        color: "#FF0055"
    },
    {
        id: 16,
        roman: "XVI",
        name: "The Black Swan",
        arcana: "The Tower",
        icon: "⚡",
        element: "Cataclysm",
        keywords: ["Flash Crash", "Depeg Event", "Structural Failure", "Unforeseen Chaos"],
        upright: "Sudden systemic market collapse. Flash liquidation cascades wiping out billions in seconds.",
        inverted: "A narrow escape from a catastrophic depeg or protocol exploit.",
        alphaDirective: "Always maintain dry cash/stablecoin reserves to buy the catastrophic dip.",
        sentiment: "Maximum Turbulence (Volatility: 100%)",
        color: "#FF0055"
    },
    {
        id: 17,
        roman: "XVII",
        name: "The 1000x Moonshot",
        arcana: "The Star",
        icon: "⭐",
        element: "Hope",
        keywords: ["Asymmetric Payoff", "Visionary Protocol", "Generational Alpha", "Inspiration"],
        upright: "A rare asymmetric opportunity with 1000x upside potential. Clear skies and pristine market conditions.",
        inverted: "Hopium illusions and false promises from unverified founders.",
        alphaDirective: "Invest an asymmetric amount you can afford to lose completely for life-changing upside.",
        sentiment: "Transcendent Bullish (Hope: 97%)",
        color: "#00F0FF"
    },
    {
        id: 18,
        roman: "XVIII",
        name: "Market FUD & Illusions",
        arcana: "The Moon",
        icon: "🌑",
        element: "Subconscious",
        keywords: ["Wash Trading", "Spoofing", "Media Panic", "Psychological Fog"],
        upright: "Heavy market fog, media manipulation, and panic selling. What seems terrifying is an illusion.",
        inverted: "The fog clears, exposing predatory manipulation and revealing true market direction.",
        alphaDirective: "Do not react to breaking media headlines; look only at on-chain liquidity flows.",
        sentiment: "Extreme FUD / Fear (Opportunity: 90%)",
        color: "#64748B"
    },
    {
        id: 19,
        roman: "XIX",
        name: "The All-Time High",
        arcana: "The Sun",
        icon: "☀️",
        element: "Radiance",
        keywords: ["Generational Wealth", "Pure Euphoria", "Peak Alpha", "Victory"],
        upright: "Magnificent parabolic expansion breaking into uncharted price discovery. Absolute financial triumph.",
        inverted: "Overconfidence, boasting, and failing to secure profits before the cycle peaks.",
        alphaDirective: "Scale out profits systematically into hard assets and secure your victory.",
        sentiment: "Euphoric Peak (Generational: 100%)",
        color: "#FFB800"
    },
    {
        id: 20,
        roman: "XX",
        name: "The Backtest Audit",
        arcana: "Judgement",
        icon: "🎺",
        element: "Awakening",
        keywords: ["Statistical Reckoning", "True Edge Revealed", "P-Value Verification", "Audit"],
        upright: "A moment of supreme clarity. Your quantitative system is mathematically validated and ready for scale.",
        inverted: "Harsh reality check: your strategy was overfitted to a single bull run.",
        alphaDirective: "Be honest with your trading journal metrics. Data never lies.",
        sentiment: "Definitive Audit (Validity: 93%)",
        color: "#39FF14"
    },
    {
        id: 21,
        roman: "XXI",
        name: "The Agent Swarm",
        arcana: "The World",
        icon: "🌐",
        element: "Mastery",
        keywords: ["Autonomous AI", "Global Optimization", "Decentralized Singularity", "Full Cycle"],
        upright: "Total mastery over the quantitative domain. Autonomous AI agent swarms executing multi-market strategies with zero human friction.",
        inverted: "Incomplete system loop requiring continuous manual patching.",
        alphaDirective: "Deploy multi-agent consensus networks and let algorithms execute the vision.",
        sentiment: "Universal Mastery (Alpha: 100%)",
        color: "#C084FC"
    }
];
